// 欄位英文 key -> 中文顯示標題 (User UI)
export const COLUMN_LABELS: Record<string, string> = {
  year: '出生年份',
  ganzhi: '干支年份',
  stem: '天干',
  branch: '地支',
  stem_element: '天干五行',
  branch_element: '地支五行',
  organ: '關聯臟腑',
  constitution: '體質特點',
  risk_system: '易感系統',
  symptom: '常見症狀',
  food1: '推薦食物 1',
  food1_effect: '食物 1 功效',
  food2: '推薦食物 2',
  food2_effect: '食物 2 功效',
  exercise1: '推薦運動 1',
  exercise1_effect: '運動 1 功效',
  exercise2: '推薦運動 2',
  exercise2_effect: '運動 2 功效',
  tcm_advice: '中醫養生建議',
  herb_medical: '常用藥材',
  herb_constitution: '體質調理藥材',
  video: '參考影片',
}

export const SEARCH_ALL_KEY = '__all__'

// 可搜尋的欄位選項 (key -> 中文)，「全部」為第一項
export const SEARCHABLE_COLUMNS: { key: string; label: string }[] = [
  { key: SEARCH_ALL_KEY, label: '全部' },
  { key: 'year', label: '出生年份' },
  { key: 'ganzhi', label: '干支年份' },
  { key: 'stem', label: '天干' },
  { key: 'branch', label: '地支' },
  { key: 'stem_element', label: '天干五行' },
  { key: 'branch_element', label: '地支五行' },
  { key: 'organ', label: '關聯臟腑' },
  { key: 'constitution', label: '體質特點' },
  { key: 'risk_system', label: '易感系統' },
  { key: 'symptom', label: '常見症狀' },
  { key: 'food1', label: '推薦食物 1' },
  { key: 'food1_effect', label: '食物 1 功效' },
  { key: 'food2', label: '推薦食物 2' },
  { key: 'food2_effect', label: '食物 2 功效' },
  { key: 'exercise1', label: '推薦運動 1' },
  { key: 'exercise1_effect', label: '運動 1 功效' },
  { key: 'exercise2', label: '推薦運動 2' },
  { key: 'exercise2_effect', label: '運動 2 功效' },
  { key: 'tcm_advice', label: '中醫養生建議' },
  { key: 'herb_medical', label: '常用藥材' },
  { key: 'herb_constitution', label: '體質調理藥材' },
  { key: 'video', label: '參考影片' },
]
